name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    strategy:
      matrix:
        include:
          - os: macos-13
            arch: amd64
            runner_arch: intel
          - os: macos-14
            arch: arm64
            runner_arch: apple-silicon
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Generate embedded binaries
        run: go generate ./...

      - name: Build application
        run: wails build -platform darwin/${{ matrix.arch }}

      - name: Create release archive
        run: |
          cd build/bin
          tar -czf ../../kleinpdf-macos-${{ matrix.runner_arch }}.tar.gz KleinPDF.app
          cd ../..

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kleinpdf-macos-${{ matrix.runner_arch }}
          path: kleinpdf-macos-${{ matrix.runner_arch }}.tar.gz

  release:
    needs: build-macos
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            kleinpdf-macos-intel/kleinpdf-macos-intel.tar.gz
            kleinpdf-macos-apple-silicon/kleinpdf-macos-apple-silicon.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}